"""make_groups_table

Revision ID: a4737b247e0c
Revises: a753dc8729bc
Create Date: 2025-04-02 00:20:29.683334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4737b247e0c'
down_revision: Union[str, None] = 'a753dc8729bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # check if table exists
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'groups' in inspector.get_table_names():
        return
    if 'user_group' in inspector.get_table_names():
        return
    # create the groups table
    # create the user_group table
    op.create_table(
        'groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'user_group',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_index(op.f('ix_user_group_user_id'), 'user_group', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_group_user_id'), table_name='user_group')
    op.drop_table('user_group')
    op.drop_table('groups')
    # ### end Alembic commands ###
